### ISSUE TITLE
Docker container reference seems to be broken in 'make.sh'

### ISSUE THREAD

**Issue by ddm** [cesanta/smart.js#16] opened 2015-08-18 18:31 UTC
In the `platforms/esp8266/make.sh` file, the referenced docker container is:

    docker.cesanta.com:5000/esp8266-build-oss:1.3.0-cesanta

It seems that the corresponding docker repository is empty:

    Unable to find image 'docker.cesanta.com:5000/esp8266-build-oss:1.3.0-cesanta' locally
    Pulling repository docker.cesanta.com:5000/esp8266-build-oss
    Error: image esp8266-build-oss:1.3.0-cesanta not found

Changing the `make.sh`file seems to fix the issue:

    SDK=cesanta/esp8266-build-oss

Is the container located at https://hub.docker.com/r/cesanta/esp8266-build-oss/ still valid for build?

**Comment by mmikulicic** [comment] 2015-08-18 20:13
The image in the docker hub repo has a quite old SDK and it's not compatible with latest smartjs. 

Thanks for reporting, I'll take a look

**Comment by mmikulicic** [comment] 2015-08-19 21:25
which version of docker do you use?

**Comment by ddm** [comment] 2015-08-20 06:37
Docker version 1.8.1, build d12ea79

Dimitri del Marmol

dimitri.delmarmol@gmail.com
+32 485 88 49 40

**Comment by mmikulicic** [comment] 2015-08-20 07:38
Issue caused by https://github.com/docker/docker/issues/15640 affecting https://github.com/cesanta/docker_auth/issues/22

In the meantime I synced the image to cesanta/esp8266-build-oss:1.3.0-cesanta

**Comment by ddm** [comment] 2015-08-20 10:41
Perfect, I modified `make.sh` and it works

    SDK=cesanta/esp8266-build-oss:1.3.0-cesanta

**Comment by rojer** [comment] 2015-08-20 13:39
this should be fixed now with cesanta/docker_auth#23

**Closed by rojer** 2015-08-20 13:39 UTC
